apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
spec:
  type : ClusterIP
  selector:
    app: ds-kusc00201 # This label must match the pod template's labels & immutable after creation
  ports:
  - port: 80
    name: nginx
    protocol: TCP
    targetPort: 80 # This is the port on the pod that the service will forward