apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: ds-kusc00201
  name: ds-kusc00201
spec:
  updateStrategy:
    type: "RollingUpdate"
  selector:
    matchLabels:
      app: ds-kusc00201 # This label must match the pod template's labels & immutable after creation
  template:
    metadata:
      labels:
        app: ds-kusc00201
    spec:
      containers:
        - name: nginx
          image: nginx:latest
      tolerations:  
        - key: "node-role.kubernetes.io/master" # matches the taint key on master nodes
          effect: "NoSchedule"
          operator: "Exists"

