apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-data
spec:
  accessModes: 
    - ReadOnlyMany
  capacity: 
    storage: 1Gi
  hostPath:
    path: /srv/app-data
  #storageClassName: "standard"
