apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb
  namespace: mariadb
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: mariadb-pv # Bind to specific PV
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi