apiVersion: v1
kind: Pod
metadata:
  name: pod-01
spec:
  volumes:
  - name: my-pv
    persistentVolumeClaim:
      claimName: my-pvc
  containers:
  - name: pod-01
    image: busybox
    command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
    volumeMounts:
    - name: my-pv
      mountPath: /data