apiVersion: v1
kind: Pod
metadata:
  name: kucc8
spec:
  containers:
  - name: nginx-pod
    image: nginx
  - name: redis-pod
    image: redis
  - name: memcached-pod
    image: memcached
  - name: consul-pod
    image: hashicorp/consul