apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: utility-api-hpa
spec:
  #behavior:
  #  scaleDown:
  #    stabilizationWindowSeconds: 30 # time to wait before scaling down ( default 300 seconds)
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: utility-api
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
