apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    imagePullPolicy: IfNotPresent
  tolerations:
  - key: "restricted"
    operator: "Equal" 
    value: "worker01"
    effect: "NoSchedule"
  nodeSelector:
    kubernetes.io/hostname: 133-worker