apiVersion: v1
kind: Namespace
metadata:
  name: sp-culator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
  namespace: sp-culator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
        - name: nginx
          image: nginx:1.24
          # < deliberately no containerPort exposed >
          command:
            - /bin/sh
            - -c
            - |
              exec nginx -g 'daemon off;'

