apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
  - name: nginx-pod
    image: nginx
    ports:
    - containerPort: 80
  - name: redis-pod
    image: redis
  - name: http-echo
    image: hashicorp/http-echo
    args:
     - "-text=welcome to hc"
     - "-listen=:8080"

  

