apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
# Simulate cert-manager CRDs installed by applying a representative CRD manifest
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: certificates.cert-manager.io
spec:
  group: cert-manager.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              description: "Specification defines desired state of the certificate"
              type: object
              properties:
                subject:
                  type: object
                  description: "Subject fields for the certificate"
                  properties:
                    organizations:
                      type: array
                      items:
                        type: string
                issuerRef:
                  type: object
                  description: "Reference to issuer"
  scope: Namespaced
  names:
    kind: Certificate
    plural: certificates
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: issuers.cert-manager.io
spec:
  group: cert-manager.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
  scope: Namespaced
  names:
    kind: Issuer
    plural: issuers