apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint
  namespace: limit-test
spec:
  limits:
  - default: # this section defines default limits
      cpu: 200m
      memory: 100Mi
    defaultRequest: # this section defines default requests
      cpu: 100m
      memory: 50Mi 
    max: # max and min define the limit range
      memory: "500Mi"
    type: Container

