apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  #volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  local: # represents the directly-attached storage with node affinity
    path: /storage/data # path to the volume on the node
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - 133-worker
  storageClassName: fast-storage