apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-logger
  namespace: priority
spec:
  replicas: 2
  selector:
    matchLabels:
      app: busybox-logger
  template:
    metadata:
      labels:
        app: busybox-logger
    spec:
      containers:
      - name: busybox
        image: busybox:1.35
        command: ["/bin/sh", "-c"]
        args:
          - |
            while true; do
              echo "\$(date): busybox-logger is running with priority: \${PRIORITY_CLASS:-default}"
              sleep 10
            done
        env:
        - name: PRIORITY_CLASS
          value: "none-yet"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"